<a href="https://colab.research.google.com/github/sensein/asd-ai-scoping-review/blob/main/scripts/PRISMA_pipeline_Fabio/csv_to_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Mount Google Drive
from google.colab import drive as gdrive
import os
import csv
import pandas as pd
import pandas as pd
from collections import OrderedDict

In [ ]:
gdrive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
workspace = "/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/PubMed"

In [ ]:
# Folder containing .bib file
csv_folder = f"{workspace}/csv/"

# Output CSV file
output_csv = f"{workspace}/autism.csv"

output_csv_formatted = f"{workspace}/autism_formatted.csv"

In [ ]:
# Get a list of all CSV files in the folder
csv_files = [file for file in os.listdir(csv_folder) if file.endswith('.csv')]

# Check if there are any CSV files in the folder
if len(csv_files) == 0:
    print("No CSV files found in the folder.")
else:
    # Initialize an empty DataFrame to store the merged data
    merged_data = pd.DataFrame()

    # Loop through the CSV files and merge them into the DataFrame
    for csv_file in csv_files:
        file_path = os.path.join(csv_folder, csv_file)
        print(file_path)
        df = pd.read_csv(file_path)
        merged_data = merged_data.append(df, ignore_index=True)

    # Save the merged data to the output CSV file
    merged_data.to_csv(output_csv, index=False)

    print(f"Merged data saved to {output_csv}")

<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
<ipython-input-8-56164ce21ace>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)

Merged data saved to /content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/PubMed/autism.csv

In [ ]:
df = pd.read_csv(output_csv)
df

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI
0,25655905,"Asperger's syndrome: diagnosis, comorbidity an...","Tarazi FI, Sahli ZT, Pleskow J, Mousa SA.",Expert Rev Neurother. 2015 Mar;15(3):281-93. d...,Tarazi FI,Expert Rev Neurother,2015,2015/02/07,NaN,NaN,10.1586/14737175.2015.1009898
1,23986012,Management of children with autism spectrum di...,"Delli K, Reichart PA, Bornstein MM, Livas C.",Med Oral Patol Oral Cir Bucal. 2013 Nov 1;18(6...,Delli K,Med Oral Patol Oral Cir Bucal,2013,2013/08/30,PMC3854078,NaN,10.4317/medoral.19084
2,23808126,Diagnosis and management of autism in adults,"Valkanova V, Rhodes F, Allan CL.","Practitioner. 2013 May;257(1761):13-6, 2-3.",Valkanova V,Practitioner,2013,2013/07/02,NaN,NaN,NaN
3,22545843,"Deficit, difference, or both? Autism and neuro...","Kapp SK, Gillespie-Lynch K, Sherman LE, Hutman T.",Dev Psychol. 2013 Jan;49(1):59-71. doi: 10.103...,Kapp SK,Dev Psychol,2013,2012/05/02,NaN,NaN,10.1037/a0028353
4,25108395,The epidemiology and global burden of autism s...,"Baxter AJ, Brugha TS, Erskine HE, Scheurer RW,...",Psychol Med. 2015 Feb;45(3):601-13. doi: 10.10...,Baxter AJ,Psychol Med,2015,2014/08/11,NaN,NaN,10.1017/S003329171400172X
...,...,...,...,...,...,...,...,...,...,...,...
58439,37022988,Infant feeding method and special educational ...,"Adams LJ, Pell JP, Mackay DF, Clark D, King A,...",PLoS Med. 2023 Apr 6;20(4):e1004191. doi: 10.1...,Adams LJ,PLoS Med,2023,2023/04/06,PMC10079126,NaN,10.1371/journal.pmed.1004191
58440,36993720,A novel SMARCC1 -mutant BAFopathy implicates e...,"Singh AK, Viviano S, Allington G, McGee S, Kiz...",medRxiv. 2023 Mar 20:2023.03.19.23287455. doi:...,Singh AK,medRxiv,2023,2023/03/30,PMC10055611,NaN,10.1101/2023.03.19.23287455
58441,33620844,Human Growth and Development,"Balasundaram P, Avulakunta ID.",2023 Mar 8. In: StatPearls [Internet]. Treasur...,Balasundaram PAvulakunta ID,StatPearls,2023,2023/03/08,NaN,NaN,NaN
58442,30000958,Marine Oils,NaN,2023 Aug 15. Drugs and Lactation Database (Lac...,NaN,Drugs and Lactation Database (LactMed®),2006,2023/08/15,NaN,NaN,NaN
58443,36749096,Preimplantation genetic testing and child heal...,"Ginström Ernstad E, Hanson C, Wånggren K, Thur...",Hum Reprod. 2023 Apr 3;38(4):739-750. doi: 10....,Ginström Ernstad E,Hum Reprod,2023,2023/02/07,PMC10068295,NaN,10.1093/humrep/dead021

In [ ]:
df.columns

Index(['PMID', 'Title', 'Authors', 'Citation', 'First Author', 'Journal/Book',
       'Publication Year', 'Create Date', 'PMCID', 'NIHMS ID', 'DOI'],
      dtype='object')

In [ ]:
df['Abstract'] = None
df['Keywords'] = None
df['URL'] = None

In [ ]:
# Define a dictionary to map the old column names to the new ones
column_mapping = OrderedDict([
    ('Title', 'Title'),
    ('Abstract', 'Abstract'),
    ('Keywords', 'Keywords'),
    ('DOI', 'DOI'),
    ('URL', 'URL'),
    ('Authors', 'Authors'),
    ('Journal/Book', 'Venue'),
    ('Publication Year', 'Year')
])

column_order = ['Title', 'Abstract', 'Keywords', 'DOI', 'URL', 'Authors', 'Venue', 'Year']

# Rename the columns based on the mapping
df.rename(columns=column_mapping, inplace=True)

# List of columns to drop
columns_to_drop = [col for col in df.columns if col not in column_mapping.values()]

# Drop the unwanted columns
df.drop(columns=columns_to_drop, inplace=True)

df = df[column_order]

In [ ]:
df.to_csv(output_csv_formatted, index=False)

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year
0,"Asperger's syndrome: diagnosis, comorbidity an...",None,None,10.1586/14737175.2015.1009898,None,"Tarazi FI, Sahli ZT, Pleskow J, Mousa SA.",Expert Rev Neurother,2015
1,Management of children with autism spectrum di...,None,None,10.4317/medoral.19084,None,"Delli K, Reichart PA, Bornstein MM, Livas C.",Med Oral Patol Oral Cir Bucal,2013
2,Diagnosis and management of autism in adults,None,None,NaN,None,"Valkanova V, Rhodes F, Allan CL.",Practitioner,2013
3,"Deficit, difference, or both? Autism and neuro...",None,None,10.1037/a0028353,None,"Kapp SK, Gillespie-Lynch K, Sherman LE, Hutman T.",Dev Psychol,2013
4,The epidemiology and global burden of autism s...,None,None,10.1017/S003329171400172X,None,"Baxter AJ, Brugha TS, Erskine HE, Scheurer RW,...",Psychol Med,2015
...,...,...,...,...,...,...,...,...
58439,Infant feeding method and special educational ...,None,None,10.1371/journal.pmed.1004191,None,"Adams LJ, Pell JP, Mackay DF, Clark D, King A,...",PLoS Med,2023
58440,A novel SMARCC1 -mutant BAFopathy implicates e...,None,None,10.1101/2023.03.19.23287455,None,"Singh AK, Viviano S, Allington G, McGee S, Kiz...",medRxiv,2023
58441,Human Growth and Development,None,None,NaN,None,"Balasundaram P, Avulakunta ID.",StatPearls,2023
58442,Marine Oils,None,None,NaN,None,NaN,Drugs and Lactation Database (LactMed®),2006
58443,Preimplantation genetic testing and child heal...,None,None,10.1093/humrep/dead021,None,"Ginström Ernstad E, Hanson C, Wånggren K, Thur...",Hum Reprod,2023